import streamlit as st
from PIL import Image

st.set_page_config(page_title="PinwormAI", layout="centered")

# ---------------- Green Theme Styling ----------------

st.markdown("""
<style>

body {
background-color:white;
}

h1,h2,h3 {
color:#2E7D32;
}

.stButton>button {
background-color:#2E7D32;
color:white;
font-size:17px;
font-weight:bold;
border-radius:8px;
height:50px;
width:100%;
}

.stButton>button:hover {
background-color:#1B5E20;
color:white;
}

</style>
""", unsafe_allow_html=True)

# ---------------- Header ----------------

def header():

    col1, col2, col3 = st.columns([2,6,1])

    with col1:
        st.image("assets/logos/tnau_logo.png", width=160)

    with col2:
        st.markdown(
            "<h1 style='margin-bottom:0;'>PinwormAI</h1>",
            unsafe_allow_html=True
        )
        st.markdown(
            "<p style='font-size:18px;color:#2E7D32;'>AI-based Tomato Pinworm Detection</p>",
            unsafe_allow_html=True
        )

    with col3:
        if st.button("🏠 Home"):
            st.session_state.page = "home"

    st.divider()

# ---------------- Navigation ----------------

if "page" not in st.session_state:
    st.session_state.page = "home"

# ---------------- HOME PAGE ----------------

if st.session_state.page == "home":

    header()

    st.write("""
PinwormAI is an artificial intelligence-based diagnostic tool developed to assist farmers and agricultural professionals in detecting Tomato Pinworm (*Tuta absoluta*) infestations from plant images. The application analyzes images captured from tomato plant parts such as leaves, fruits, stems, or adult moths and predicts the likelihood of pest infestation using a trained convolutional neural network model. The system aims to provide rapid identification and support timely pest management decisions in tomato cultivation.
""")

    st.write("")

    col1, col2 = st.columns(2)

    with col1:
        if st.button("📷 Capture Image"):
            st.session_state.page = "plant_part"

    with col2:
        uploaded = st.file_uploader("Upload Image", type=["jpg","png","jpeg"])

        if uploaded:
            st.session_state.image = uploaded
            st.session_state.page = "scan"

# ---------------- SELECT PLANT PART ----------------

elif st.session_state.page == "plant_part":

    header()

    st.subheader("Select the plant part to scan")

    st.write("""
Different plant parts may exhibit visible symptoms of tomato pinworm infestation. Select the plant component that you want to analyze. The system will evaluate the captured image and determine whether the observed symptoms correspond to *Tuta absoluta* infestation or represent other non-target conditions.
""")

    col1, col2 = st.columns(2)

    with col1:

        if st.button("🌿 Leaf"):
            st.session_state.page = "scan"

        if st.button("🌱 Stem"):
            st.session_state.page = "scan"

    with col2:

        if st.button("🍅 Fruit"):
            st.session_state.page = "scan"

        if st.button("🦋 Adult Moth"):
            st.session_state.page = "scan"

# ---------------- SCAN PAGE ----------------

elif st.session_state.page == "scan":

    header()

    st.subheader("Scan Image")

    image = st.file_uploader("Upload plant image for analysis", type=["jpg","png","jpeg"])

    if image:

        img = Image.open(image)

        st.image(img, use_column_width=True)

        if st.button("Scan Image"):

            predictions = [
                ("Adult moth", 96.4, "assets/results/adult_prediction.jpg"),
                ("Leaf damage symptom", 92.1, "assets/results/leaf_symptom_prediction.jpg"),
                ("Non-target", 95.2, "assets/results/non_target.jpg")
            ]

            st.session_state.results = predictions
            st.session_state.page = "results"

# ---------------- RESULTS PAGE ----------------

elif st.session_state.page == "results":

    header()

    st.subheader("Detection Results")

    st.write("""
The following results represent the predicted classes generated by the artificial intelligence model along with their corresponding confidence values. Higher confidence values indicate a stronger probability that the uploaded image belongs to the predicted category.
""")

    results = st.session_state.results

    for r in results:

        col1, col2 = st.columns([1,4])

        with col1:
            st.image(r[2], width=100)

        with col2:
            if st.button(f"{r[0]} — Confidence {r[1]}%"):
                st.session_state.page = "details"

# ---------------- DETAILS PAGE ----------------

elif st.session_state.page == "details":

    header()

    st.subheader("Tomato Pinworm (*Tuta absoluta*)")

    with st.expander("Description"):

        st.write("""
Tomato pinworm, *Tuta absoluta*, is one of the most destructive pests of tomato crops worldwide. The larvae feed internally within plant tissues and create mines in leaves, stems, and fruits. Continuous feeding damage significantly reduces crop yield and fruit quality. Due to its high reproductive potential and rapid spread, this invasive pest has become a major constraint to sustainable tomato production.
""")

        st.image("assets/symptoms/leaf_damage_1.jpg")
        st.image("assets/symptoms/fruit_damage_1.jpg")

    with st.expander("Symptoms"):

        st.write("""
Infested tomato plants commonly show serpentine leaf mines caused by larval feeding within leaf tissues. Damaged leaves gradually turn necrotic and dry. Larvae may also bore into developing fruits and create internal galleries that make the fruits unmarketable. Severe infestations can lead to substantial yield losses if appropriate management strategies are not implemented.
""")

    with st.expander("Life Cycle"):

        st.write("""
The life cycle of *Tuta absoluta* consists of four developmental stages including egg, larva, pupa, and adult moth. Female moths lay eggs on tomato leaves and stems. The emerging larvae penetrate plant tissues and feed internally before pupating either on the plant or in the soil. Adult moths subsequently emerge and continue the infestation cycle.
""")

        col1, col2, col3, col4 = st.columns(4)

        col1.image("assets/lifecycle/egg.jpg", caption="Egg")
        col2.image("assets/lifecycle/larva.jpg", caption="Larva")
        col3.image("assets/lifecycle/pupa.jpg", caption="Pupa")
        col4.image("assets/lifecycle/adult.jpg", caption="Adult")

    with st.expander("Management"):

        st.write("""
• Remove and destroy infested leaves and fruits to reduce pest population.

• Install pheromone traps at approximately 16 traps per acre to monitor and reduce adult moth populations.

• Avoid continuous cultivation of solanaceous crops in the same field to minimize pest carryover.

• Release egg parasitoids such as *Trichogramma* species as part of biological control strategies.

• Apply recommended insecticides such as Chlorantraniliprole 18.5% SC or Cyantraniliprole 10.26% OD when pest incidence reaches economic threshold levels.
""")